### ISSUE TITLE
OnChaseEnded doesn't return the last targeted player.

### ISSUE THREAD

**Issue by GalladeR475** [Sythivo/AIEngine#1]
# FIX
On line **65** of the Chase mechanism/module, you'll see a declaration of `OnStateChange` to be something like this:
![image](https://github.com/Sythivo/AIEngine/assets/92134856/4de73f06-8c38-44de-9646-9e6655d3268a)
As you can see, `OnChaseEnded` doesn't fire with the last targeted player.
Just a little above, on line **56** you can see that `OnChaseEnded` will be fired with the last targeted player, but only happens if there is another player in sight.
![image](https://github.com/Sythivo/AIEngine/assets/92134856/140ab9a4-3e63-4898-adde-671390744c8e)
But for single-player games, this is not *that* handy.
Here's my fix:
![image](https://github.com/Sythivo/AIEngine/assets/92134856/4c0a8d59-1520-4b2e-a0e6-88c0836d1d1f)

**Comment by GalladeR475** [comment]
Let me know if you're having any issues!

**Comment by Sythivo** [comment]
This is on purpose.

When there is no player passed into `OnChaseEnded` event, it signifies that the AI has completely ended, chasing no one.
When a player is passed, it represents that it is chasing a new player, so it would pass the previous player that it chased.

Also note this is part of the examples, which should be viewed as examples I created, and you can improve on or modify.

**Comment by GalladeR475** [comment]
+Reminder:
AIEngine can be modified to whatever you like, just as Sythivo said.
![image](https://github.com/Sythivo/AIEngine/assets/92134856/ce434f19-7a35-4a31-a672-d0d2ca0d052d)
As you can see, the `?` indicates that the Signal would either return a player or `nil`.
This was done by design.
I hope you understand!

**Comment by S7vie** [comment]
Interesting
I didn't know about that, thanks!

**Comment by Sythivo** [comment]
Modifying the AIEngine source isn't suggested but you are free to do so. You can copy the Examples template to design your own system.

**Comment by Sythivo** [comment]
I would close this issue as it appears to be solved. 😅
