### ISSUE TITLE
[AIEngine] AI stutters after jumpscare

### ISSUE THREAD

**Issue by GalladeR475** [Sythivo/AIEngine#7]
@Sythivo 
hey there, I made the mimic AI using AIEngine and I wanted to know how I could fix this bug.
basically, the AI starts stuttering [during movement] after the jumpscare.
All I do is set the walk speed of the AI using `AI.Movement:SetWalkSpeed(...)`.
## Start Event
![image](https://github.com/Sythivo/AIEngine/assets/92134856/f8eada48-12e8-4f5c-8e6c-081deb14d9f1)
## Jumpscare Mechanism
![image](https://github.com/Sythivo/AIEngine/assets/92134856/520deeb0-11a1-4e11-b19a-eed5b6e480c8)

# Here is the [issue](https://youtu.be/oj_dRno5XPM)

**Comment by Sythivo** [comment]
If you ever `Anchor` the AI, the network ownership can reset, from server to automatic, make sure after Unanchoring the AI, you [`SetNetworkOwner`](https://create.roblox.com/docs/reference/engine/classes/Part#SetNetworkOwner).

**Comment by GalladeR475** [comment]
My current AIEngine code doesn't anchor the HumanoidRootPart, but this solution resolved it.
Thank you.
![image](https://github.com/Sythivo/AIEngine/assets/92134856/f9493dd3-c5b8-4670-8b97-716b7b1ad58c)
# OTHER REFERENCES TRUNCATED
