### ISSUE TITLE
[AI] unable to locate nearby waypoints

### ISSUE THREAD

**Issue by S7vie** [Sythivo/AIEngine#8]
@Sythivo 
So, first of all; I added *prints* to the "`Roam`" module
![image](https://github.com/Sythivo/AIEngine/assets/138582066/8fdcf31a-0aa1-48b2-bd5d-adfbfc2942ce)

The Map has [**23**] total `RoamPoints`. (It's very closed in some parts)
[The map isn't too small or too big, it's just a mildly closed map]
And yes. I tried modifying the `PivotOffset` a lot, didn't help. Well, almost didn't. It would make the AI go in a loop of going to the same 2 `RoamPoints` and getting Stuck for 4s. Instead of not moving at all.

I did add more `RoamPoints` (close to the AI) but that made it worse.
Modified the `AgentParams`, barely helped.

# Before you say "It's a issue with the map", then yes. I'm aware. I can't do much about that except edit the code, and I have to get this done soon elsewise, the game is 100% getting delayed.

And I'm not even the Founder of it, making it worse for me.
(saying this so you know I need urgent help)

And finally, the stairs are designed in a way in which you can't add wedges to most which bugs the AI out a lot too. So, I made the "CanJump" `true` but it didn't work because you didn't implement that feature. I would implement it myself but I have a hard time with others code.

**Comment by GalladeR475** [comment]
What are you trying to *do* exactly?
From what I've read, you want the AI to wander near 2 nearby `RoamPoints`.
Why don't you use `table.sort` on the copy of the `RoamPoints` list and index it?

```lua
table.sort(CopyOfRoamPoints, function(a: BasePart, b: BasePart)
    -- logic
end);

local first = CopyOfRoamPoints[1];
loca second = CopyOfRoamPoints[2];
```

# OR
You could sort the main `RoamPoints` table.

**Comment by S7vie** [comment]
listen, that's not it. the AI has a lot of trouble with roaming, i'm not trying to make it roam to specific points or anything. i've tried my best (to my knowledge at least) but failed.

**Comment by S7vie** [comment]
like I said before, changing the pivotoffset and agentparams barely helped. it's the map that's causing and there's almost nothing i can do about that except fix the AI

**Comment by S7vie** [comment]
if I put the exact same AI with the same AIEngine module stuff, on a baseplate it works just about right.

**Comment by GalladeR475** [comment]
> If I put the exact same AI with the same AIEngine module stuff, on a baseplate it works just about right.

Did you modify the source?
If so, what modifications?
Do you have custom mechanisms or are you sticking to the examples?

**Comment by S7vie** [comment]
Yeah I modified but it I manually reverted it to normal, I will go have a look at the code in some time and no, no custom mechanisms at the moment.

**Comment by S7vie** [comment]
I'm talking about before I inserted it to a Baseplate

**Comment by Sythivo** [comment]
Example modules aren't really the best, but they should give you a head start on refining it. `CanJump` can be modified within the agent params created, I suggest using that for maps with high gaps, and you could copy the `CyclicLoopAsync` code to support jumping if you need, but best option might be to have high walking height to have no jumping but still allow walking though high gaps seemlessly.

Another note, this framework likely would've gotten updates while developing `The Mimic` but in recent times, we currently aren't using this module. It doesn't mean it's bad, it's just we developed a new system that would not be compatible with this framework.

**Comment by S7vie** [comment]
There aren't really any obstacles in the map, it's just the stairs that the AI gets stuck on so I'll have to implement jumping to the loop but for now, I'll keep the issue open.

**Comment by S7vie** [comment]
The AI also has high speed and the corners/gaps aren't that high.

**Comment by GalladeR475** [comment]
> The AI also has high speed and the corners/gaps aren't that high.

Strange. In my AI test, I jokingly set the AI's speed to 100 studs/s and it worked fine with stairs and all.
Are you sure that the model is rigged properly? Rigging issues may cause pathfinding issues as well.

**Comment by Sythivo** [comment]
Check the Navigation Map.

`File > Studio Settings > Studio > Visualization > Show Navigation Mesh`

Check the area, and the stairs should have a purple plane everywhere, if not there might be a problem with the Map's navigation.

**Comment by S7vie** [comment]
> > The AI also has high speed and the corners/gaps aren't that high.
> 
> Strange. In my AI test, I jokingly set the AI's speed to 100 studs/s and it worked fine with stairs and all. Are you sure that the model is rigged properly? Rigging issues may cause pathfinding issues as well.

It's rigged and the rigging of the bodyparts is the default Rig that Roblox has.

**Comment by S7vie** [comment]
> Check the Navigation Map.
> 
> `File > Studio Settings > Studio > Visualization > Show Navigation Mesh`
> 
> Check the area, and the stairs should have a purple plane everywhere, if not there might be a problem with the Map's navigation.

Okay, I'll go see. But there's something I wanna say, The AI for some reason, on the third `RoamPoint` tried going downstairs instead (there wasn't a `RoamPoint` there). It was completely off. Had to modify the `AgentParams` for that one.

**Comment by Sythivo** [comment]
AIEngine won't be able to provide any automatic `AgentParams` yet. `AgentParams` are manual, you would have to make the values.

**Comment by S7vie** [comment]
I know about that. Also I checked the Map's navigation, the stairs had purple plane but it was all messed up.

**Comment by S7vie** [comment]
Also, how are automatic `AgentParams` supposed to even work? (since you said "*yet*")

**Comment by GalladeR475** [comment]
> Also, how are automatic `AgentParams` supposed to even work? (since you said "_yet_")

basically something like this:

```lua
local AgentParameters = {
	AgentHeight = Humanoid.HipHeight;
	AgentRadius = HumanoidRootPart.Size.X;
	--// ...
}
```
To provide dynamic agent parameters.

**Comment by S7vie** [comment]
> > Also, how are automatic `AgentParams` supposed to even work? (since you said "_yet_")
> 
> basically something like this:
> 
> ```lua
> local AgentParameters = {
> 	AgentHeight = Humanoid.HipHeight;
> 	AgentRadius = HumanoidRootPart.Size.X;
> 	--// ...
> }
> ```
> 
> To provide dynamic agent parameters.

That's the default one, seen that everywhere.

**Comment by S7vie** [comment]
That doesn't work well sometimes
